COMP: Constrain wrapping to 2D, 3D images
4D images, enabled in the ITK 5.2 wrapping, are not currently supported.

To address:

In file included from ../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.h:172,
                 from ../../../include/itkAnisotropicDiffusionLBRImageFilter.h:28,
                 from ../../../include/itkCoherenceEnhancingDiffusionImageFilter.h:27,
                 from ../../../ITK-cp36-cp36m-manylinux2014_x64/Wrapping/Typedefs/itkCoherenceEnhancingDiffusionImageFilterSwigInterface.h:18,
                 from Wrapping/Modules/AnisotropicDiffusionLBR/itkCoherenceEnhancingDiffusionImageFilterPython.cpp:3533:
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx: In instantiation of ‘itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilType itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilFunctor::operator()(const TensorType&, const IndexType&) const [with TImage = itk::Image<double, 4>; TScalar = double; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilType = std::pair<itk::Vector<int, 12>, itk::Vector<double, 6> >; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::TensorType = itk::SymmetricSecondRankTensor<double, 4>; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::IndexType = itk::Index<4>]’:
../../../include/itkUnaryFunctorWithIndexImageFilter.h:87:9:   required from ‘void itk::UnaryFunctorWithIndexImageFilter<TInputImage, TOutputImage, TFunctor>::DynamicThreadedGenerateData(const OutputRegionType&) [with TInputImage = itk::Image<itk::SymmetricSecondRankTensor<double, 4>, 4>; TOutputImage = itk::Image<std::pair<itk::Vector<int, 12>, itk::Vector<double, 6> >, 4>; TFunctor = itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor; itk::UnaryFunctorWithIndexImageFilter<TInputImage, TOutputImage, TFunctor>::OutputRegionType = itk::ImageRegion<4>]’
../../../include/itkUnaryFunctorWithIndexImageFilter.h:73:3:   required from here
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx:138:5: error: no matching function for call to ‘itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Stencil(itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Dispatch<4>, itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::TensorType&, itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilOffsetsType&, itk::Vector<double, 6>&) const’
  138 |     this->Stencil(Dispatch<ImageDimension>(), D, offsets, stencil.second);
      |     ^~~~
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx:170:3: note: candidate: ‘static void itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilFunctor::Stencil(const itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilFunctor::Dispatch<2>&, const TensorType&, itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilOffsetsType&, itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilCoefficientsType&) [with TImage = itk::Image<double, 4>; TScalar = double; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::TensorType = itk::SymmetricSecondRankTensor<double, 4>; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilOffsetsType = itk::Vector<itk::Offset<4>, 6>; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilCoefficientsType = itk::Vector<double, 6>]’
  170 |   Stencil(const Dispatch<2> &,
      |   ^~~~~~~
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx:170:11: note:   no known conversion for argument 1 from ‘itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Dispatch<4>’ to ‘const itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Dispatch<2>&’
  170 |   Stencil(const Dispatch<2> &,
      |           ^~~~~~~~~~~~~~~~~~~
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx:225:3: note: candidate: ‘static void itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilFunctor::Stencil(const itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilFunctor::Dispatch<3>&, const TensorType&, itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilOffsetsType&, itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilCoefficientsType&) [with TImage = itk::Image<double, 4>; TScalar = double; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::TensorType = itk::SymmetricSecondRankTensor<double, 4>; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilOffsetsType = itk::Vector<itk::Offset<4>, 6>; itk::LinearAnisotropicDiffusionLBRImageFilter<TImage, TScalar>::StencilCoefficientsType = itk::Vector<double, 6>]’
  225 |   Stencil(const Dispatch<3> &,
      |   ^~~~~~~
../../../include/itkLinearAnisotropicDiffusionLBRImageFilter.hxx:225:11: note:   no known conversion for argument 1 from ‘itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Dispatch<4>’ to ‘const itk::LinearAnisotropicDiffusionLBRImageFilter<itk::Image<double, 4>, double>::StencilFunctor::Dispatch<3>&’
  225 |   Stencil(const Dispatch<3> &,
      |           ^~~~~~~~~~~~~~~~~~~