COMP: Add missing ImageToImageFilter base class #include
To address:

  ITK-src/Modules/Remote/AnisotropicDiffusionLBR/include/itkUnaryFunctorWithIndexImageFilter.h:37:28:
  error: expected template-name before '<' token